In [7]:
import sys
import numpy as np

# use () for print statement
print('Python: {}'.format(sys.version))
print('NumPy: {}'.format(np.__version__))

Python: 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy: 1.18.1


In [8]:
# define a scalar
x = 5
x

5

In [9]:
# define a vector
x = np.array((1,2,3))
x

array([1, 2, 3])

In [10]:
print("Vector dimension: {}".format(x.shape))
print("Vector size: {}".format(x.size))

Vector dimension: (3,)
Vector size: 3


In [11]:
# define a matrix
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
print("Vector dimension: {}".format(x.shape))
print("Vector size: {}".format(x.size))

Vector dimension: (3, 3)
Vector size: 9


In [13]:
# define a matrix of a given dimension
x = np.ones((3,3))

In [14]:
x


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# create a tensor -> multiple matrices -> 3D tensor
# 3x3 matrices and 3 of them
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [17]:
print("Tensor dimension: {}".format(x.shape))
print("Parameter size: {}".format(x.size))

Tensor dimension: (3, 3, 3)
Parameter size: 27


In [19]:
# indexing 
# create a matrix 5x5 and full of int
A = np.ones((5,5), dtype = np.int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [20]:
# indexing matrix element
A[0,1] = 9
print(A)

[[1 9 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [22]:
# change all elements of A to 5
A[:,:]= 5
A

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [23]:
# add index for higher dimensions
A = np.ones((5,5,5), dtype = np.int)

# assign first row a new value
# 0 element of the matrix and all three matrices in the 3D tensor
A[0:,0,0] = 6
A

array([[[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[6, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [24]:
# matrix operations
A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2), dtype = np.int)


In [25]:
A
B

array([[1, 1],
       [1, 1]])

In [26]:
B

array([[1, 1],
       [1, 1]])

In [27]:
A

matrix([[1, 2],
        [3, 4]])

In [28]:
C = A + B
C

matrix([[2, 3],
        [4, 5]])

In [29]:
D = A - B
D

matrix([[0, 1],
        [2, 3]])

In [30]:
E = A*B
E

matrix([[3, 3],
        [7, 7]])

In [31]:
# matrix transpose
A = np.array(range(9))
# shape of the matrix defined here
A = A.reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
# transpose command .T
B = A.T
B

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [33]:
C = B.T
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
C.shape

(3, 3)

In [35]:
B.shape

(3, 3)

In [36]:
B.size

9

In [42]:
# tensors (easy for computer)
A = np.ones((3,3,3,3,3,3,3,3,3,3))
A.size


59049